# Generated by Django 4.1.7 on 2023-04-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrlink',
            name='titulo',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
